# Generated by Django 4.2 on 2023-04-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoCode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
